from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('ly68l6400', src, depend = ['PKG_LY68L6400_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
