from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('ly68l6400', src, depend = ['PKG_USING_LY68L6400'], CPPPATH = CPPPATH)

Return('group')
